### ISSUE TITLE
Can't establish connection

### ISSUE THREAD

**Issue by jplt001** [Wisembly/elephant.io#160]
Hi I'm having a problem on emitting; I'm doing from my API to existing socket io project, but this keep error message showing on the resul.

exception 'ElephantIO\Exception\ServerConnectionFailureException' with message 'An error occurred while trying to establish a connection to the server' in C:\inetpub\wwwroot\testing_ground\test\node-socket-practice\vendor\dennybrandes\elephant.io\src\Engine\SocketIO\Version1X.php:180
Stack trace:
#0 C:\inetpub\wwwroot\testing_ground\test\node-socket-practice\vendor\dennybrandes\elephant.io\src\Engine\SocketIO\Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake()
#1 C:\inetpub\wwwroot\testing_ground\test\node-socket-practice\vendor\dennybrandes\elephant.io\src\Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect()
#2 C:\inetpub\wwwroot\testing_ground\test\node-socket-practice\emit.php(19): ElephantIO\Client->initialize()
#3 {main}

Here is my code: 
$version 	= new Version2X("http://localhost:12000/parking-view");
$client 	= new Client($version);
$client->initialize();

$client->read();
$client->emit('ata', ['msg'=>$msg, 'from'=>$from]);
$r = $client2->read();
$client->close();

**Comment by jplt001** [comment]
Please close this issue, I configure it out now I'm just discovered that the URL on `version2x` is only `http://localhost:12000` and the `/parking-view` is the namespace of socket.io and this must be on`$client->of("/parking-view");` before emit function.
