### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by mmt78** [Wisembly/elephant.io#179]
When I try to node server, I get the error below:
Fatal error: Uncaught ElephantIO\Exception\ServerConnectionFailureException: An error occurred while trying to establish a connection to the server in /var/www/html/shared/socket-io/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php:187 Stack trace: #0 /var/www/html/shared/socket-io/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php(48): ElephantIO\Engine\SocketIO\Version1X->handshake() #1 /var/www/html/shared/socket-io/vendor/wisembly/elephant.io/src/Client.php(60): ElephantIO\Engine\SocketIO\Version1X->connect() #2 /var/www/html/shared/classes/socket.class.php(24): ElephantIO\Client->initialize() #3 /var/www/html/dashboard/news.php(83): Socket->__construct() #4 {main} thrown in /var/www/html/shared/socket-io/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php on line 187
It is strange that when I use Version 2X still I get the same error. Actually it connects the server but throw the error and stop working.

**Comment by Taluu** [comment]
Please catch the exception and dump the content of `getErrorMessage()`.

**Comment by indigoram89** [comment]
I have the same error...

**Comment by Taluu** [comment]
Do you also have the result of `getErrorMessage()` to `null` ?

**Comment by indigoram89** [comment]
Yes, I do

**Comment by Taluu** [comment]
Which version are you using ? dev-master or 3.1 ?

**Comment by Taluu** [comment]
Sorry, meant 3.3

**Comment by indigoram89** [comment]
"wisembly/elephant.io": "^3.3",

**Comment by Taluu** [comment]
Could you then try with `dev-master` ? I'll try to do a release when I'll have enough time to do it...

**Comment by Taluu** [comment]
And if that doesn't work, could you remove the `@` on https://github.com/Wisembly/elephant.io/blob/master/src/Engine/SocketIO/Version1X.php#L196 ?

**Comment by indigoram89** [comment]
dev-master is not working

**Comment by indigoram89** [comment]
![img-2019-04-05-18-04-53](https://user-images.githubusercontent.com/10687211/55637319-6a9b8500-57cd-11e9-8d9e-aca281c7165b.png)

**Comment by Taluu** [comment]
OK now that is strange. It seems that the resource is already busy with something else (probably `socket.io` ?).

Could you maybe try a `ping` on that adress / resource ?

BTW, not really sure but your uri looks strange (it shouldn't be escaped : `use_b64=0&EIO=...`) but maybe it's the error message that does that.

**Comment by indigoram89** [comment]
yes, the error message does that

**Comment by indigoram89** [comment]
I try the same code on the server (DO) and it's working.
But I have the error on my local machine (mac os).

**Comment by Taluu** [comment]
Got no clue then on why this happens, especially as I don't have a mac. Sorry :/

**Comment by indigoram89** [comment]
Thanks anyway and good luck!

**Comment by peter279k** [comment]
I change the socket IO server dependencies and it's worked successfully.

It can look at the PR #186 to know more details.

**Comment by indigoram89** [comment]
Wow, I have found my mistake!

The trouble in ini_set("default_socket_timeout", -1);

This line was in another package which uses the elephant.io package.

Thank you guys!

**Comment by peter279k** [comment]
I think we don't let the `default_socket_timeout`  be`-1` because this will always try connecting the socket server until the connection is established.

**Comment by daryn-k** [comment]
I have the same error. Even more, this error occurred accidentally, I didn't change anything. Everything works fine in the localhost, in NodeJS, in browser ... But the real server doesn't accept any connections from PHP Client. It's so weird, I have no clue.

**Comment by akshayb007** [comment]
Hii there,

I am facing the same issue in ubuntu with php8. Everything is working fine in nodejs and browser. But not working when emit the event from laravel php.

**Comment by akshayb007** [comment]
Hello,

I am also facing the same issue in one of my project. Everything is working fine localhost, nodejs and in browser, but when i calling it from Elephant.io it's thowing : An error occurred while trying to establish a connection to the server
