### ISSUE TITLE
Not working with multiple CPU hosting

### ISSUE THREAD

**Issue by snapapplabs** [Wisembly/elephant.io#182]
<br />
<b>Fatal error</b>:  Uncaught UnexpectedValueException: The server returned an unexpected value. Expected &quot;HTTP/1.1 101&quot;, had &quot;HTTP/1.1 400&quot; in /var/www/html/yolo/api/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php:266
Stack trace:
#0 /var/www/html/yolo/api/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php(73): ElephantIO\Engine\SocketIO\Version1X-&gt;upgradeTransport()
#1 /var/www/html/yolo/api/vendor/wisembly/elephant.io/src/Client.php(60): ElephantIO\Engine\SocketIO\Version1X-&gt;connect()
#2 /var/www/html/yolo/api/api.php(757): ElephantIO\Client-&gt;initialize()
#3 /var/www/html/yolo/api/api.php(742): send_ping_notification_socket('2', 'Two', 'http://18.224.2...', '1', '1', 'One', 'http://18.224.2...', '1')
#4 /var/www/html/yolo/api/api.php(449): send_ping(Array, Array)
#5 /var/www/html/yolo/api/index.php(28): update_user('2', Array, Array)
#6 {main}
  thrown in <b>/var/www/html/yolo/api/vendor/wisembly/elephant.io/src/Engine/SocketIO/Version1X.php</b> on line <b>266</b><br />

**Comment by Taluu** [comment]
I don't get what's wrong. Wrong version maybe ?

**Comment by peter279k** [comment]
Hi @snapapplabs, could you provide the sample code that you execute?

We can try to reproduce issue and help you to find the current problem.

**Comment by MohammedElmsellem** [comment]
Hi @Taluu This error is thrown when using cluster module in nodejs

**Comment by Taluu** [comment]
From what I can see in both errors, you are hitting a 400 (bad request). So that means that either the version is wrong (2.x instead of 1.x, or something like that).

You will need to check what request is made, and try it yourself.
